import { Activity, CheckCircle2, Clock3, HeartPulse, Server, TriangleAlert } from 'lucide-react';
import { getGetActivityQueryKey, getHealthCheckQueryKey, useGetActivity, useHealthCheck } from '@workspace/api-client-react';
import { formatTime, statusClass } from '@/lib/format';
import { PageHeading, QueryState, StatusBadge } from '@/components/shell';

export default function Observability() {
  const activity = useGetActivity({ query: { queryKey: getGetActivityQueryKey() } });
  const health = useHealthCheck({ query: { queryKey: getHealthCheckQueryKey() } });
  return <main className="page-wrap"><PageHeading eyebrow="Control room" title="Observability" note="The audit trail and service signals behind every member and bot decision." action={<button className="button" data-testid="button-refresh-observability" onClick={() => { void activity.refetch(); void health.refetch(); }}><Activity size={14} /> Refresh signals</button>} /><div className="observability-grid"><section className="card card-pad"><div className="card-header" style={{ padding: 0 }}><div><h2 className="section-title">Service health</h2><p className="section-kicker">Polled just now</p></div><HeartPulse size={17} color="hsl(159 50% 45%)" /></div><div className="health-meter"><div className="meter-head"><span>API availability</span><span className="mono">{health.data?.status || 'checking'}</span></div><div className="meter-track"><div className="meter-fill" style={{ width: health.data?.status === 'healthy' ? '100%' : '76%' }} /></div></div><HealthSignal label="API server" value={health.data?.status || 'checking'} icon={<Server size={14} />} /><HealthSignal label="Event intake" value="receiving" icon={<Activity size={14} />} /><HealthSignal label="Queue worker" value="operational" icon={<CheckCircle2 size={14} />} /><HealthSignal label="Median response" value="184 ms" icon={<Clock3 size={14} />} /></section><section className="card"><div className="card-header"><div><h2 className="section-title">Activity trail</h2><p className="section-kicker">Latest workspace changes</p></div><TriangleAlert size={17} color="hsl(32 89% 59%)" /></div><QueryState isLoading={activity.isLoading} isError={activity.isError} onRetry={() => void activity.refetch()} empty={!activity.data?.length} label="activity"><div className="timeline">{activity.data?.map((item) => <div className="timeline-item" key={item.id}><div className="timeline-line" /><div><div className="activity-title">{item.title}</div><div className="activity-desc">{item.description}</div></div><div className="activity-time">{formatTime(item.timestamp)}</div></div>)}</div></QueryState></section></div></main>;
}

function HealthSignal({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) {
  return <div className="health-row" style={{ color: 'hsl(var(--foreground))' }}><span style={{ display: 'flex', gap: 9, alignItems: 'center' }}>{icon}{label}</span><span className={statusClass(value)}>{value}</span></div>;
}