import { CreditCard, Download, Search } from 'lucide-react';
import { useState } from 'react';
import { getGetPaymentsQueryKey, useGetPayments } from '@workspace/api-client-react';
import { formatDate, formatMoney, initials } from '@/lib/format';
import { PageHeading, QueryState, StatusBadge } from '@/components/shell';

const paymentStatuses = ['all', 'confirmed', 'pending', 'refunded'] as const;

export default function Payments() {
  const [status, setStatus] = useState<(typeof paymentStatuses)[number]>('all');
  const params = { status: status === 'all' ? undefined : status };
  const query = useGetPayments(params, { query: { queryKey: getGetPaymentsQueryKey(params) } });
  const total = query.data?.filter((item) => item.status === 'confirmed').reduce((sum, item) => sum + item.net, 0) ?? 0;
  return <main className="page-wrap"><PageHeading eyebrow="Money movement" title="Payments" note="A clean ledger of member payments, platform fees, and net revenue." action={<button className="button" data-testid="button-export-payments" onClick={() => window.alert('Export is ready when the payments service is connected.')}><Download size={14} /> Export ledger</button>} /><div className="metric-grid" style={{ marginBottom: 14 }}><div className="card metric-card"><div className="metric-top"><CreditCard size={15} /> Net captured</div><div className="metric-value">{formatMoney(total)}</div><div className="metric-foot">confirmed transactions</div></div><div className="card metric-card"><div className="metric-top"><Search size={15} /> Ledger rows</div><div className="metric-value">{query.data?.length ?? '—'}</div><div className="metric-foot">current view</div></div></div><div className="toolbar"><div className="toolbar-left"><select className="select" aria-label="Filter payments by status" data-testid="select-payment-status" value={status} onChange={(event) => setStatus(event.target.value as (typeof paymentStatuses)[number])}>{paymentStatuses.map((item) => <option key={item} value={item}>{item === 'all' ? 'All payment states' : item}</option>)}</select></div></div><QueryState isLoading={query.isLoading} isError={query.isError} onRetry={() => void query.refetch()} empty={!query.data?.length} label="payments"><div className="card table-card"><div className="table-scroll"><table><thead><tr><th>Member</th><th>Gross</th><th>Fee</th><th>Net</th><th>Status</th><th>Captured</th></tr></thead><tbody>{query.data?.map((payment) => <tr key={payment.id} data-testid={`row-payment-${payment.id}`}><td><div className="member-cell"><div className="avatar">{initials(payment.memberUsername)}</div><div><div className="member-name">{payment.memberUsername}</div><div className="member-handle">Payment {payment.id}</div></div></div></td><td className="amount">{formatMoney(payment.amount, payment.currency)}</td><td className="amount" style={{ color: 'hsl(var(--muted-foreground))' }}>−{formatMoney(payment.fee, payment.currency)}</td><td className="amount">{formatMoney(payment.net, payment.currency)}</td><td><StatusBadge status={payment.status} /></td><td className="mono">{formatDate(payment.createdAt)}</td></tr>)}</tbody></table></div></div></QueryState></main>;
}